data1<-read.table("/Users/bhavna/Downloads/household_power_consumption.txt", sep=";", header=TRUE, fill=TRUE)
data1$Time<-strptime(paste(data1$Date,data1$Time), format="%d/%m/%Y %H:%M:%S")
data1$Date<-as.Date(data1$Date,format="%d/%m/%Y")
data2<-subset(data1, data1$Date=="2007-02-02"| data1$Date=="2007-02-01")
png("plot2.png", width=480, height=480)
plot.new()
plot(data2$Time, data2$Global_active_power, type="n", ylab="Global Active Power (Kilowatts)", xlab="")
lines(data2$Time, data2$Global_active_power)
dev.off()
