data1<-read.table("/Users/bhavna/Downloads/household_power_consumption.txt", sep=";", header=TRUE, na.strings="?")
data1$Time<-strptime(paste(data1$Date,data1$Time), format="%d/%m/%Y %H:%M:%S")
data1$Date<-as.Date(data1$Date,format="%d/%m/%Y")
data2<-subset(data1, data1$Date=="2007-02-02"| data1$Date=="2007-02-01")
png("plot4.png", width=480, height=480)
plot.new()
par(mfrow=c(2,2))
with(data2, {
	plot(data2$Time, data2$Global_active_power, type="n", ylab="Global Active Power (Kilowatts)", xlab="")
	lines(data2$Time, data2$Global_active_power)
	plot(data2$Time, data2$Voltage, type="n", ylab="Voltage", xlab="datetime")
	lines(data2$Time, data2$Voltage)
	plot(data2$Time, data2$Sub_metering_1, type="n", ylab="Energy sub metering", xlab="")
	lines(data2$Time, data2$Sub_metering_1)
	lines(data2$Time, data2$Sub_metering_2, col="red")
	lines(data2$Time, data2$Sub_metering_3, col="blue")
	legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black", "red", "blue"))
	plot(data2$Time, data2$Global_reactive_power, type="n", ylab="Global_Reactive_Power", xlab="datetime")
	lines(data2$Time, data2$Global_reactive_power)
})
dev.off()
